config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'drivers#home'
  match '/auth/:provider/callback', to: 'sessions#auth', via: [:get, :post]
  get '/signin', to: 'sessions#new'
  post '/signin', to: 'sessions#create'
  get '/signout', to: 'sessions#destroy'
  resources :drivers, only: [:new, :create, :edit, :update]
  resources :drivers, only: [:show] do
    resources :vehicles, only: [:index, :show, :new, :destroy]
    resources :races, only: [:index]
  end
  resources :vehicles, only: [:show, :create]
  resources :tracks, only: [:index, :new, :create]
  resources :tracks, only: [:show] do
    resources :races, only: [:new, :create]
  end
  resources :races, only: [:create]
  post '/drivers/:id/vehicles/:id', to: 'vehicles#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/driver.rb
class Driver < ApplicationRecord
    has_secure_password
    has_many :tracks, through: :races
    has_many :races
    has_many :vehicles
    validates :username, :first_name, :last_name, :experience, :age, :country, presence: true
    validates :password, presence: true, on: :create

    def full_name
        self.first_name + " " + self.last_name
    end
end

app/models/race.rb
class Race < ApplicationRecord
    belongs_to :driver
    belongs_to :track
    validates :track_time, presence: true

    def self.fastest_times
        order('track_time ASC')
    end
end

app/models/track.rb
class Track < ApplicationRecord
    has_many :drivers, through: :races
    has_many :races
    validates :name, :location, :weather, :distance, presence: true

    def raced?
        if self.raced == true
            "Raced"
        else
            "Not Raced"
        end
    end
end

app/models/vehicle.rb
class Vehicle < ApplicationRecord
    belongs_to :driver
    validates :year, :make, :model, :trim, :horsepower, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :driver_layout, :require_login, :is_logged_in?, :current_user

    def driver_layout
      @driver = Driver.find_by(id: session[:driver_id])
    end
  
    def require_login
      redirect_to '/' unless session.include? :driver_id
    end

    def is_logged_in?
      if session[:driver_id]
        redirect_to '/'
      end
    end

    def current_user
      if @driver = Driver.find_by(id: params[:id])
        @driver = Driver.find_by(id: params[:id])
      else
        @driver = Driver.find_by(id: session[:driver_id])
      end
      if session[:driver_id] != @driver.id
        redirect_to driver_path(session[:driver_id])
      end
    end
end

app/controllers/drivers_controller.rb
class DriversController < ApplicationController
    layout 'application'
    before_action :driver_layout, only: [:home]
    before_action :require_login, only: [:show]
    before_action :current_user, only: [:show, :edit, :update]

    def home
    end

    def new
        @driver = Driver.new
    end

    def create
        @driver = Driver.new(driver_params)
        if @driver.save
            session[:driver_id] = @driver.id
            redirect_to driver_path(@driver)
        else
            render 'new'
        end
    end
    
    def show
        @driver = Driver.find_by(id: params[:id])
    end

    def edit
        @driver = Driver.find_by(id: params[:id])
    end

    def update
        @driver = Driver.find_by(id: params[:id])
        @driver.update(driver_params)
        redirect_to driver_path(@driver)
    end

    private

    def driver_params
        params.require(:driver).permit(:username, :first_name, :last_name, :password, :age, :experience, :country)
    end
end

app/controllers/races_controller.rb
class RacesController < ApplicationController
    layout "application"
    before_action :driver_layout

    def new
        @race = Race.new
        @track = Track.find_by(id: params[:track_id])
    end

    def create
        race = Race.create(race_params)
        @track = Track.find_by(name: params[:race][:track])
        @track.races << race
        @driver.races << race
        redirect_to driver_races_path(@driver)
    end

    def index
        @races = @driver.races.fastest_times
    end

    private

    def race_params
        params.require(:race).permit(:track_time)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    layout "application"
    before_action :driver_layout
    before_action :is_logged_in?, only: [:new, :create]
    skip_before_action :driver_layout, only: [:auth]

    def new
    end

    def create
        if @driver = Driver.find_by(username: params[:username])
            if @driver.authenticate(params[:password])
                session[:driver_id] = @driver.id
                redirect_to driver_path(@driver)
            else
                flash[:error] = 'Invalid password'
                render 'new'
            end
        else
            flash[:error] = 'User does not exist'
            render 'new'
        end
    end

    def auth
        pp request.env['omniauth.auth']
        @driver = Driver.find_by(username: request.env['omniauth.auth']['info']['nickname'])
        #session[:username] = request.env['omniauth.auth']['info']['nickname']
        session[:driver_id] = @driver.id
        session[:omniauth_data] = request.env['omniauth.auth']
        redirect_to root_path
    end

    def destroy
       session.delete :driver_id
       redirect_to "/" 
    end
end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController
    layout "application"
    before_action :driver_layout

    def new
        @track = Track.new
    end

    def create
        @track = Track.new(track_params)
        if @track.save
            redirect_to tracks_path
        else
            render 'new'
        end
    end

    def index
        @tracks = Track.all
    end

    def show
        @track = Track.find_by(id: params[:id])
    end

    private

    def track_params
        params.require(:track).permit(:name, :location, :weather, :distance)
    end
end

app/controllers/vehicles_controller.rb
class VehiclesController < ApplicationController
    layout "application"
    before_action :driver_layout
    before_action :current_user

    def index
        
    end

    def new
        @vehicle = Vehicle.new
    end

    def create
        @vehicle = Vehicle.new(vehicle_params)
        @driver.vehicles << @vehicle
        if @vehicle.save 
            redirect_to driver_vehicles_path(@driver)
        else
            render 'new'
        end
    end

    def show
        @vehicle = Vehicle.find_by(id: params[:id])
    end

    def destroy
        @vehicle = Vehicle.find_by(id: params[:id])
        @vehicle.delete
        redirect_to driver_vehicles_path(@driver)
    end

    private

    def vehicle_params
        params.require(:vehicle).permit(:year, :make, :model, :horsepower, :trim)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/drivers_helper.rb
module DriversHelper
end

app/helpers/races_helper.rb
module RacesHelper
end

app/helpers/tracks_helper.rb
module TracksHelper
end

app/helpers/vehicles_helper.rb
module VehiclesHelper
end

app/views/drivers/_form.html.erb
<% if @driver.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(@driver.errors.count, "error") %>
      prohibited this post from being saved:
    </h2>
 
    <ul>
    <% @driver.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_for @driver do |f| %>
    <%= f.label :username %>
    <br>
    <%= f.text_field :username %>
    <br>
    <%= f.label :first_name %>
    <br>
    <%= f.text_field :first_name %>
    <br>
    <%= f.label :last_name %>
    <br>
    <%= f.text_field :last_name %>
    <br>
    <%= f.label :age %>
    <br>
    <%= f.number_field :age %>
    <br>
    <%= f.label :experience, "How many years have you been racing?" %>
    <br>
    <%= f.number_field :experience %>
    <br>
    <%= f.label :country, "What country were you born in?" %>
    <br>
    <%= f.text_field :country %>
    <br>
    <%= f.label :password %>
    <br>
    <%= f.password_field :password %>
    <br>
    <%= f.submit %>
<% end %>

app/views/drivers/edit.html.erb
<h3>Edit Your Info</h3>

<%= render 'form' %>

app/views/drivers/home.html.erb
<div>
    <img style="vertical-align:middle;margin:0px 250px" width="800" height="400" src="https://previews.123rf.com/images/bigmouse/bigmouse1706/bigmouse170600073/80502525-cartoon-car-racing-sport-professional-competition-vector.jpg">
    <h1 align="center">Welcome to Bear Drag Strip!</h1>
</div>

app/views/drivers/new.html.erb
<h3>Register Below</h3>

<%= render 'form' %>

app/views/drivers/show.html.erb
<p>Full Name: <%= @driver.full_name %></p>
<p>Age: <%= @driver.age %></p>
<p>Experience: <%= @driver.experience %></p>
<p>Country: <%= @driver.country %></p>
<%= link_to "Edit Info", edit_driver_path(@driver) %>
<br>
<br>
<br>
<%= link_to "Vehicles >>", driver_vehicles_path(@driver) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <style>
ul {
  list-style-type: none;
  margin: 0;
  padding: 0;
  overflow: hidden;
  background-color: #333;
}

li {
  float: left;
}

li a {
  display: block;
  color: white;
  text-align: center;
  padding: 14px 16px;
  text-decoration: none;
}

li a:hover {
  background-color: #111;
}
</style>
</head>
  <body>
    <ul>
      <li><a class="active" href="/">Home</a></li>
      <% if session[:driver_id].nil? %>
        <li><%= link_to "Sign Up", new_driver_path %></li>
        <li><%= link_to "Log In", signin_path %></li>
      <% else %>
        <li><%= link_to "#{@driver.username}'s Profile", driver_path(@driver) %></li>
        <li><%= link_to "Tracks", tracks_path %></li>
        <li><%= link_to "My Races", driver_races_path(@driver) %></li>
        <li><%= link_to "Log Out", signout_path  %></li>
      <% end %>
    </ul>
    <%= yield %>
  </body>
</html>

app/views/races/index.html.erb
<h1>Your Races</h1>
<br>
<% @races.each do |race| %>
    <p><%= race.track_time %> seconds - <%= race.track.name %></p>
<% end %>

app/views/races/new.html.erb
<p>Thank you for racing at <%= @track.name %>!</p>
<br>
<%= form_for @race do |f| %>
    
    <%= f.hidden_field :track, value: @track.name %>
    <br>
    <%= f.label :track_time, "Please submit your official time:" %>
    <%= f.text_field :track_time %>    
    <br>
    <br>
    <%= f.submit "Submit Time" %>
<% end %>

app/views/tracks/_form.html.erb
<% if @track.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(@track.errors.count, "error") %>
      prohibited this post from being saved:
    </h2>
 
    <ul>
    <% @track.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_for @track do |f| %>
    <%= f.label :name %>
    <br>
    <%= f.text_field :name %>
    <br>
    <%= f.label :location %>
    <br>
    <%= f.text_field :location %>
    <br>
    <%= f.label :weather %>
    <br>
    <%= f.text_field :weather %>
    <br>
    <%= f.label :distance, "Distance (miles)" %>
    <br>
    <%= f.text_field :distance%>
    <br>
    <%= f.submit %>
<% end %>

app/views/tracks/index.html.erb
<h1>All Tracks</h1>
<p><%= link_to "Add New Track", new_track_path %></p>
<br>
<br>
<% @tracks.each do |track| %>
    <h2><%= link_to track.name, track_path(track) %></h2>
<% end %>

app/views/tracks/new.html.erb
<h3>New Track</h3>

<%= render 'form' %>

app/views/tracks/show.html.erb
<h1><%= @track.name %></h1>
<p><%= @track.location %></p>
<p><%= @track.weather %></p>
<p><%= @track.distance %></p>
<br>
<%= link_to '<button type="button">Race</button>'.html_safe, new_track_race_path(@track) %>

app/views/vehicles/_form.html.erb
<% if @vehicle.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(@vehicle.errors.count, "error") %>
      prohibited this, please try again:
    </h2>
 
    <ul>
    <% @vehicle.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_for @vehicle do |f| %>
    <%= f.label :year %>
    <br>
    <%= f.text_field :year %>
    <br>
    <%= f.label :make %>
    <br>
    <%= f.text_field :make %>
    <br>
    <%= f.label :model %>
    <br>
    <%= f.text_field :model %>
    <br>
    <%= f.label :trim %>
    <br>
    <%= f.text_field :trim %>
    <br>
    <%= f.label :horsepower %>
    <br>
    <%= f.number_field :horsepower %>
    <br>
    <%= f.submit %>
<% end %>

app/views/vehicles/index.html.erb
<h1>All Your Vehicles</h1>
<%= link_to "Add a Vehicle", new_driver_vehicle_path(@driver) %>
<br>
<br>
<% @driver.vehicles.each do |vehicle| %>
    <li><%= vehicle.year %> <%= vehicle.make %> <%= vehicle.model%> <%= link_to "View", vehicle_path(vehicle) %></li><li><%= button_to "Remove", driver_vehicle_path(@driver, vehicle), mehtod: :delete %></li>
    <br><br><br><br>
<% end %>

app/views/vehicles/new.html.erb
<h1>Add a New Vehicle</h1>

<%= render 'form' %>

app/views/vehicles/show.html.erb
<h1>Vehicle Info</h1>
<br>
<p>Horsepower: <%= @vehicle.horsepower %>
<p>Vehicle Trim: <%= @vehicle.trim %>